"""add last_reset_token to users

Revision ID: 4499cbc313a2
Revises: 681b1255adb9
Create Date: 2025-10-12 19:44:25.652329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4499cbc313a2'
down_revision: Union[str, Sequence[str], None] = '681b1255adb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_reset_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_last_reset_token'), 'users', ['last_reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_reset_token'), table_name='users')
    op.drop_column('users', 'last_reset_token')
    # ### end Alembic commands ###
