"""crear tabla materiales

Revision ID: 57eedecb2cb4
Revises: 
Create Date: 2025-11-08 10:19:49.403249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57eedecb2cb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.Column('medida', sa.String(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiales_id'), 'materiales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materiales_id'), table_name='materiales')
    op.drop_table('materiales')
    # ### end Alembic commands ###
