"""Crear tablas solicitudes y solicitud_items

Revision ID: fb25102ff39c
Revises: 57eedecb2cb4
Create Date: 2025-11-13 23:46:54.939532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb25102ff39c'
down_revision: Union[str, Sequence[str], None] = '57eedecb2cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_cedula', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pendiente', 'en_proceso', 'completado', name='solicitudstatus'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_cedula'], ['users.cedula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_cliente_cedula'), 'solicitudes', ['cliente_cedula'], unique=False)
    op.create_index(op.f('ix_solicitudes_id'), 'solicitudes', ['id'], unique=False)
    op.create_table('solicitud_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_items_id'), 'solicitud_items', ['id'], unique=False)
    op.create_index(op.f('ix_solicitud_items_solicitud_id'), 'solicitud_items', ['solicitud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitud_items_solicitud_id'), table_name='solicitud_items')
    op.drop_index(op.f('ix_solicitud_items_id'), table_name='solicitud_items')
    op.drop_table('solicitud_items')
    op.drop_index(op.f('ix_solicitudes_id'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_cliente_cedula'), table_name='solicitudes')
    op.drop_table('solicitudes')
    # ### end Alembic commands ###
